version = "3.7.3"
runner.dialect = scala213

maxColumn = 100
indent.main = 2
indent.callSite = 2
indent.defnSite = 2

align.preset = none

newlines.beforeCurlyLambdaParams = false
newlines.afterCurlyLambdaParams = squash

docstrings.style = Asterisk
docstrings.wrap = no

rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
